mysite/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url('polls/', include('polls.urls')),
    url('tasks/', include('tasks.urls')),
    url('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('', views.index, name='index'),
]

tasks/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'tasks'

urlpatterns = [
    url('index/', views.index, name='index'),
    url(r'^deleteTask/(?P<id>[0-9]+)/', views.deleteTask, name='deleteTask'),
    url(r'^addTask/', views.addTask, name='addTask'),
    url(r'^getEditTask/(?P<id>[0-9]+)/', views.getEditTask, name='getEditTask'),
    url(r'^editTask/', views.editTask, name='editTask'),
    url(r'^markCompleted/(?P<id>[0-9]+)/', views.markCompleted, name='markCompleted')
    #url(r'^createTask/', views.createTask, name='createTask')
]

polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('published date')

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

tasks/models.py
from django.db import models
import datetime
from django.utils import timezone

class User(models.Model):
    userName = models.CharField(max_length = 50)
    password = models.TextField()


class Task(models.Model):
    userId = models.ForeignKey(User, on_delete = models.CASCADE)
    taskName = models.TextField()
    createdTime = models.DateTimeField(default=timezone.now)
    completionDate = models.DateTimeField()
    isDone = models.IntegerField()

polls/views.py
from django.http import HttpResponse

def index(response):
    return HttpResponse("Hello All! Polls Index Page!")

tasks/views.py
from django.http import HttpResponse
from django.shortcuts import render
from tasks.models import User, Task

def index(request):
    tasks = Task.objects.all()
    return render(request, 'tasks/home.html', {'tasks': tasks})

def deleteTask(request, id):
    tasks = Task.objects.all()
    print(id)
    task = Task.objects.get(id=id)
    task.delete()
    return render(request, 'tasks/home.html', {'tasks': tasks})

def addTask(request):
    user = User.objects.get(id=1)
    task = None
    
    if request.GET and request.GET['taskName'] != None:
        task = Task.objects.create(userId=user, taskName=request.GET['taskName'], completionDate=request.GET['completionDate'], isDone=0)
    return render(request, 'tasks/addTask.html', {'task': task})    

def getEditTask(request, id):
    task = Task.objects.get(id=id)
    print(task)
    return render(request, 'tasks/editTask.html', {'task': task})

def editTask(request):
    id = request.GET['id']
    result = Task.objects.filter(pk=id).update(taskName=request.GET['taskName'], completionDate=request.GET['completionDate'])
    tasks = Task.objects.all()
    return render(request, 'tasks/home.html', {'tasks': tasks})

def markCompleted(request, id):
    result = Task.objects.filter(pk=id).update(isDone=1)
    tasks = Task.objects.all()
    return render(request, 'tasks/home.html', {'tasks': tasks})

tasks/templates/tasks/addTask.html
{% include 'tasks/header.html' %}
<div class="row">
    <div class="col-md-2 col-md-offset-10">
        <a href="{% url 'tasks:index' %}" class="remove-decorate"><h4>Home</h4></a>
    </div>
</div>
<div class="div-contain">
    {% if task != None %}
        <div class="row"><h4 class="font-white">Task created successfully!</h4></div>
    {% endif %}
    <h3>Create your task</h3>
    <form action="{% url 'tasks:addTask' %}"> 
        <div class="row margin-top-20">
            <div class="col-md-12">
                <input class="form-control" required id="taskName" name="taskName" placeholder="Task">
            </div>
        </div>
        <div class="row margin-top-20">
            <div class="col-md-12">
                <input class="form-control" required name="completionDate" id="completionDate" placeholder="Completion date">
            </div>
        </div>
        <input type="submit" class="btn trans-btn margin-top-20">
    </form>
    <script>
        jQuery('#completionDate').datetimepicker({
            format:'Y-m-d H:i:s',
        });
    </script>
</div>
{% include 'tasks/footer.html' %}

tasks/templates/tasks/editTask.html
{% include 'tasks/header.html' %}
<div class="row">
    <div class="col-md-2 col-md-offset-10">
        <a href="{% url 'tasks:index' %}" class="remove-decorate"><h4>Home</h4></a>
    </div>
</div>
<div class="div-contain">
    {% if task != None %}
        <!--<div class="row">Task edited successfully!</div>-->
    {% endif %}
    <h3>Edit your task</h3>
    <form action="{% url 'tasks:editTask'%}"> 
        <div class="row margin-top-20">
            <div class="col-md-12">
                <input class="form-control" id="taskName" name="taskName" 
                value="{{task.taskName}}" placeholder="Task">
            </div>
        </div>
        <div class="row margin-top-20">
            <div class="col-md-12">
                <input class="form-control" name="completionDate" id="completionDate" 
                value="{{task.completionDate}}" placeholder="Completion date">
            </div>
        </div>
        <input type="hidden" name="id" id="id" value="{{task.id}}">
        <input type="submit" class="btn trans-btn margin-top-20">
    </form>
    <script>
        jQuery('#completionDate').datetimepicker({
            format:'Y-m-d H:i:s',
        });
    </script>
</div>
{% include 'tasks/footer.html' %}

tasks/templates/tasks/footer.html
            </div>
        </div>
        {% load static %}
        <script src="{% static 'js/index.js' %}"></script>
        <script src="{% static 'js/confetti.js' %}"></script>
    </body>
</html>

tasks/templates/tasks/header.html
<!DOCTYPE html> 
    <head>
        <title>Tasks</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.css" >
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>
        
    </head>
    <body>
        <div class="container custom-container">
            <div class="box">

tasks/templates/tasks/home.html
{% include 'tasks/header.html' %}
<canvas hidden id="canvas"></canvas>
{% if tasks == None %}
    <div>No Tasks yet!</div>

{% else %}
    
    <div class="row margin-top-20">
        <div class="col-md-5 col-md-offset-5"><h3 class="main-heading">Your Tasks</h3></div>
        <div class="col-md-2">
            <button class="btn btn-primary addTask">
                <a class="remove-decorate font-white" href="{% url 'tasks:addTask' %}">
                    <i class="fa fa-plus"></i>
                </a>
            </button> 
        </div>
    </div>
    <!--<div class="row margin-bottom-20 margin-top-20 headings">
        <div class="col-md-3"><strong><h4></h4></strong></div>
        <div class="col-md-2"><strong><h4>Task Name</h4></strong></div>
        <div class="col-md-2"><strong><h4>Is it done ?</h4></strong></div>
        <div class="col-md-2"><strong><h4>Created at</h4></strong></div>
    </div>-->

    <div class="tasks">
        {% for task in tasks %} 
            <div class="row margin-bottom-10">
                <div class="col-md-3">
                    <div class='middle-align'>
                        <a href='{% url "tasks:markCompleted" id=task.id %}'><button class='btn btn-check isDoneBtn'><i class='fa fa-check'></i></button></a>
                    </div>
                </div>

                <input type="hidden" id="taskid" name="taskid" value="{{task.id}}">
                <div class="col-md-2 middle-align">
                    <span class="font-strong">{{task.taskName}}</span>
                </div>
                <div class="col-md-2 middle-align">
                    {% if task.isDone == 1 %} 
                        <span class="completed">Completed</span>
                    {% else %} 
                        <span class="pending">Pending</span>
                    {% endif %}
                </div>
                <div class="col-md-2 middle-align">
                    created on: 
                    {{task.createdTime}}
                </div>
                <div class="col-md-1">
                    <a href="{% url 'tasks:getEditTask' id=task.id %}">
                        <button class="btn btn-sm btn-primary edit editBtn font-white remove-decorate"><i class="fa fa-pencil"></i></button>
                    </a>
                </div>
                <div class="col-md-1">
                    <button class="btn btn-sm btn-danger delete deleteBtn">
                        <a href="{% url 'tasks:deleteTask' id=task.id %}" class="remove-decorate font-white"><i class="fa fa-trash"></i></a>
                    </button>
                </div>
            </div>
            
        {% endfor %} 
    </div>
        
{% endif %}

{% include 'tasks/footer.html' %}